Repository DJPORTILLO30/CRM-UMG, pull requests merged in 2022-10, with the labels that each got.

#15 Creación de carpetas y archivos para "Permisos"
  controllers/permisos/permisos.js
  models/permisos/permisos.js
  routes/permisos/permisos.js
Labels: InDevelopment

#16 Carpetas y archivos para "usuarios"
  app.js
  config/mysql.js
  controllers/usuarios/usuarios.js
  models/usuarios/usuarios.js
  routes/usuarios/usuarios.js
Labels: InDevelopment

#17 Creación de carpetas, rutas y controladores.
  controllers/roles/roles.js
  models/roles/roles.js
  routes/roles/roles.js
Labels: InDevelopment

#13 Feature Contactos
  controllers/contactos/contactos.js
  models/contactos/contactos.js
  routes/contactos.js
Labels: documentation, invalid, InDevelopment

#14 Feature Campañas
  controllers/campañas/campañas.js
  models/campañas/campañas.js
  routes/campañas.js
Labels: documentation, invalid, InDevelopment

#18 Se crearon controladores y rutas.
  controllers/llamadas/llamadas.js
  models/llamadas/llamadas.js
  package.json
  routes/llamadas/llamadas.js
  test/llamadas/helper/helperData
  test/llamadas/llamadas.test.js
  utils/querys/Llamadas.sql
  validators/llamadas.js
Labels: invalid, InDevelopment

#19 Feature negocios
  controllers/negocio/negocio.js
  models/negocio/negocio.js
  routes/negocio/negocio.js
  test/negocios/helper/helperData.js
  test/negocios/negocios.test.js
  utils/handlers/handleProperties.js
  utils/querys/Negocio.sql
  validators/negocio.js
Labels: InDevelopment
